version: '3'

services:
        database:
                container_name: database
                image: 'docker.io/bitnami/mariadb:10.2-debian-10'
#REMEMBER TO SET PASSWORDS AND USER
                environment:
                        - MARIADB_USER=my_user
                        - MARIADB_DATABASE=my_database
                        - MARIADB_PASSWORD=my_password

                volumes:
                        - ./db:/var/lib/mysql

                command: tail -F /dev/null
        
        backend:
                tty: true
                container_name: backend
                image: 'docker.io/bitnami/laravel:7-debian-10'
#REMEMBER TO SET PASSWORD AND USER
                environment:
                        - DB_HOST=database 
                        - DB_USERNAME=my_user
                        - DB_DATABASE=my_database
                        - DB_PASSWORD=my_password
                depends_on:
                        - database
                ports:
                        - 3000:3000
                volumes:
                        - ./backend:/app
                command: tail -F /dev/null
        
        frontend:
                container_name: frontend
                build:
                        context: ./frontend/
                        dockerfile: Dockerfile
                volumes: 
                        - './frontend/:/app'
                        - '/app/node_modules'
                ports:
                        - 8080:8080
