version: '3'

services:
        db:
                container_name: db
                image: 'mariadb:10'
#REMEMBER TO SET PASSWORDS AND USER
                environment:
                        - MYSQL_ROOT_PASSWORD=SuperSecretAdminPassword
                        - MYSQL_USER=invisman
                        - MYSQL_DATABASE=Inventory
                        - MYSQL_PASSWORD=P4ssW0rd

                volumes:
                        - ./db:/var/lib/mysql
                        - type: bind
                          source: ./my.cnf
                          target: /etc/mysql/my.cnf
        backend:
                container_name: backend
                build:
                        context: ./backend/
                        dockerfile: Dockerfile
                depends_on:
                        - db
                links:
                        - db
                environment:
                        - DB_HOST=db:3306
                        - DB_TYPE=mysql
                        - DB_USERNAME=invisman
                        - DB_DATABASE=Inventory
                        - DB_PASSWORD=P4ssW0rd
                volumes:
                        - ./backend/:/var/www/html/

                ports:
                        - "8100:80"
                stdin_open: true
                tty: true
        
        frontend:
                container_name: frontend
                build:
                        context: ./frontend/
                        dockerfile: Dockerfile
                volumes: 
                        - './frontend/:/app'
                        - '/app/node_modules'
                ports:
                        - 8080:8080
